//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wardrobe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outfit
    {
        public int OutfitID { get; set; }
        public int ShirtID { get; set; }
        public int BottomID { get; set; }
        public Nullable<int> AccessID { get; set; }
        public int ShoesID { get; set; }
        public int SeasonID { get; set; }
        public int OccasionID { get; set; }
        public int ColorID { get; set; }
    }
}
